version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: spring-rest-api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
