spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: 
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
## create-drop = clear data
